default:
  image: maven:3.9.6-openjdk-17-slim

variables:
  # 可以填 TAG 和 HEAD
  TAG: 0.0.1
  PORT: 9000
  DOCKER_IMAGE: image
  DOCKER_TAG: v0.0.1


stages:
  - build
  - deploy

maven-build:
  stage: build
  tag:
    - docker
  before_script:
    - mvn -version
    - java -version
  script:
    - |
      git fetch --tags
      git checkout $TAG
    - mvn clean package
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    # 推送到docker仓库
    # docker login ***
    # docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  tags:
    - ssh-test
  stage: deploy
  needs:
    - build
  before_script:
    - java -version
  script:
    - docker run $DOCKER_IMAGE:$DOCKER_TAG


